change Dockerfile and docker-compose.yaml to use .env.production (prev commit used .env.local so it was connect to backend on vercel) so now frontend is connected to backend on localhost:3000

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,25 +1,54 @@
 FROM node:20-alpine3.19 as base
-WORKDIR /app
-COPY package*.json ./
-RUN npm install --production
 
-# FROM base as builder
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+
+# 2. Rebuild the source code only when needed
+# FROM base AS builder
 # WORKDIR /app
-# COPY --from=base /app/node_modules ./node_modules
+# COPY --from=deps /app/node_modules ./node_modules
 # COPY . .
+# This will do the trick, use the corresponding env file for each environment.
 # RUN npm run build
 
-FROM base as production
+# 3. Production image, copy all the files and run next
+FROM base AS runner
 WORKDIR /app
+
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
 ENV NODE_ENV=production
 
-COPY . .
-# COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
-# COPY --from=builder /app/node_modules ./node_modules
-# COPY --from=builder /app/package.json ./package.json
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
+
 # COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+
+USER nextjs
 
 EXPOSE 5000
 
-CMD ["node", "server.js"]
+ENV PORT 5000
+
+CMD HOSTNAME=localhost node server.js
